# https://docs.gradle.org/current/userguide/version_catalogs.html#sec::toml-dependencies-format

[versions]
assertj-core = "3.27.7"
checker = "4.2.2"
filesystemview-base = "1.0.0-rc.1"
filesystemview-fx   = "1.0.0-rc.1"
javafx = "26.0.2"
jsemver = "3.1.0"
junit-jupiter = "6.0.1"

[libraries]
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj-core" }
checker = { group = "org.checkerframework", name = "checker", version.ref = "checker" }
filesystemview-base = { group = "de.bernd-michaely", name = "lib-filesystem-view-base", version.ref = "filesystemview-base" }
filesystemview-fx   = { group = "de.bernd-michaely", name = "lib-filesystem-view-fx",   version.ref = "filesystemview-fx" }
jsemver = { group = "de.bernd-michaely", name = "jsemver", version.ref = "jsemver" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[bundles]
assertj = [ "assertj-core" ]
filesystemview = [ "filesystemview-base", "filesystemview-fx" ]
